name: Web Automation Tests

on:
  workflow_dispatch

jobs:
  test:
    timeout-minutes: 180
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1
      - name: Clear Cache
        run: npm cache clean --force
      - name: Install dependencies and run tests
        run: npm install && npm playwright test
