name: Web Automation Tests

on:
  workflow_dispatch

jobs:
  test:
    timeout-minutes: 180
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17.x"
      - run: npm init playwright@latest

      - name: Test in Region - "${{ env.REGION }}"
        run: npx playwright test
